name: Kotlin CICD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set up GIT
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.mail jan-hendrik.hausner@outlook

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Lint API
        uses: stoplightio/spectral-action@v0.8.11
        with:
          file_glob: 'config/openapi/spec/bamconfigbackend.json'
          spectral_ruleset: 'config/openapi/spectral/.spectral.json'

      - name: Build with Gradle
        run: ./gradlew generateTypescriptDataModel --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.BAM_AUTHORIZATION_TOKEN }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.71.0
        id: tag-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: minor
          RELEASE_BRANCHES: master
          PRERELEASE_SUFFIX: beta
          GIT_API_TAGGING: false

      - name: Update Typescript package version
        run: npm version ${{ steps.tag-version.outputs.new_tag }} --prefix ./build/${GITHUB_REPOSITORY#*/}/typescript

      - name: Publish Typescript library
        run: npm publish --folder ./build/${GITHUB_REPOSITORY#*/}/typescript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker Image
        run: docker build . --file Dockerfile --build-arg GITHUB_TOKEN=${{ secrets.BAM_AUTHORIZATION_TOKEN }} --tag ${{ github.repository }}:${{ steps.tag-version.outputs.new_tag }} --tag ${{ github.repository }}:latest

      - name: Push versioned Docker Image
        run: docker push ${{ github.repository }}:${{ steps.tag-version.outputs.new_tag }}

      - name: Push latest Docker Image
        run: docker push ${{ github.repository }}:latest